# Generated by Django 3.1.3 on 2021-08-16 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('contraseña', models.CharField(max_length=20, verbose_name='cotraseña')),
            ],
        ),
        migrations.CreateModel(
            name='Publicaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=150, verbose_name='contenido')),
                ('anexo', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plataforma.user')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='producto')),
                ('precio', models.FloatField()),
                ('laboratorio', models.CharField(max_length=50, verbose_name='laboratorio')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plataforma.user')),
            ],
        ),
    ]
