# Generated by Django 3.1.3 on 2021-08-16 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Producto',
        ),
        migrations.RenameModel(
            old_name='Publicaciones',
            new_name='Publicacion',
        ),
    ]
