# Generated by Django 3.1.3 on 2021-08-16 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0003_auto_20210816_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(max_length=15, verbose_name='nombre'),
        ),
    ]
