# Generated by Django 3.1.3 on 2021-08-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0004_auto_20210816_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellidos', models.CharField(max_length=20, verbose_name='apellidos')),
                ('usuario', models.CharField(max_length=15, verbose_name='usuario')),
                ('contraseña', models.CharField(max_length=20, verbose_name='cotraseña')),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plataforma.usuario'),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plataforma.usuario'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
