# Generated by Django 3.1.3 on 2021-08-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0005_auto_20210816_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='contraseña',
            field=models.CharField(max_length=20, verbose_name='contraseña'),
        ),
    ]
