# Generated by Django 3.1.3 on 2021-08-16 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0006_auto_20210816_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='user',
            field=models.IntegerField(),
        ),
    ]
