# Generated by Django 3.1.3 on 2021-08-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0007_auto_20210816_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='user',
            field=models.CharField(max_length=15, verbose_name='usuario'),
        ),
    ]
