# Generated by Django 3.1.3 on 2021-08-16 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0011_auto_20210816_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plataforma.usuario'),
        ),
    ]
