# Generated by Django 3.1.3 on 2021-08-16 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Plataforma', '0013_auto_20210816_1657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='anexo',
        ),
    ]
